### ISSUE TITLE
Open-API Schemas: Client Generation

### ISSUE THREAD

**Issue by diesalbla** [higherkindness/skeuomorph#108]
After recent work by @BeniVF, Skeumorph is able to parse an API specification in the OpenAPI 3.0 format (a.k.a. Swagger), and of generating an http4s client library for it. However, HTTP being a somewhat complicated protocol, not all features are supported from the beginning. 

The goal of this over-issue is to keep track of the features that are pending to be supported by Skeumorph / OpenAPI. 

- [ ] Support for query parameters: elements in query parameters should be included as input parameters of the client method. 
- [ ] Support for getting a URI from the `Location` Header of a `201 Created` response, usually for  a `POST` or `PUT` request, that has created a new entity

**Comment by juanpedromoreno** [comment]
Closed by https://github.com/higherkindness/skeuomorph/pulls?q=is%3Apr+is%3Aclosed+label%3A%22Open+API+%28aka.+Swagger%29%22
