### ISSUE TITLE
Fix proto imports cannot see other proto folders

### ISSUE THREAD

**Issue by AdrianRaFo** [higherkindness/skeuomorph#111]
@SemanticBeeng discovered an issue on the `Protobuf` imports where if we have 2 folders with `proto` files even on the same module we are not able to import from one folder to another (you can see the diff [here](https://github.com/AdrianRaFo/RPC-Proto-Seed/compare/arf-multi-protocol?expand=1) ).

The real problem is we are facing here is that we are missing the `-I` argument on the `Protobuf` compilation which should allow us to add the other folder on our compilation AFAIK.

**Comment by SemanticBeeng** [comment]
Example of generated code

![image](https://user-images.githubusercontent.com/9296536/61039670-37a0f880-a39d-11e9-8c03-3f491192c561.png)

**Comment by AdrianRaFo** [comment]
I guess is a skeuomorph one but people in charge of this could verify it

**Comment by bilki** [comment]
I'm taking a look at this. My first impression for imports is that we need to pipe `srcGenSourceDirs` (or even better, `srcGenIDLTargetDir`) from Mu gen plugin to skeuomorph, maybe adjusting paths, as @AdrianRaFo suggested.

**Comment by bilki** [comment]
Ok, I have located the place where slash should be replaced with dots (or whatever other adjustments that we may need to do): https://github.com/higherkindness/skeuomorph/blob/master/src/main/scala/higherkindness/skeuomorph/protobuf/ParseProto.scala#L117

Let me test a bit more and I will open a PR fixing these bugs.

**Comment by SemanticBeeng** [comment]
@bilki thanks - please also check if these soft links can be avoided. 

Cannot see how unless `mu` passes down to `skeumorph` knowledge about inter-module dependencies.
Event then work in Intellij would not be nice (without the softlinks and imports)

**Comment by bilki** [comment]
@SemanticBeeng I don't think we could get rid of those soft links :( Anyway, check the new PRs that solve the problem of the nested folders containing imported proto files.
