### ISSUE TITLE
Protobuf oneOf to generate coproducts without Option-ality

### ISSUE THREAD

**Issue by SemanticBeeng** [higherkindness/skeuomorph#113]
In `proto3` there is no `required` constraint available.

As a consequence this

```
oneof value {
  A : a = 1;
  B : B = 2;
}
```
generates
```
Option[A] :+: Option[B] :+: CNil
```

Proposing the `Option`-ality is removed to generate `shapeless` `A :+: B :+: CNil` instead.

Rationale:

1. The `Option`-ality seems redundant in the coproduct for evident reasons: if A is present in the `coproduct` then it is not optional.
2. Generates more complex than necessary service apis.
3. Slows down the runtime marshalling.

Given that `skeuomorph` is schema transformation library the user should have more flexibility at the time use from `mu` (time of service api design) and not be bound by the semantics of source IDL (context https://github.com/higherkindness/skeuomorph/issues/91).

Resources
1.  https://stackoverflow.com/questions/42955621/require-a-oneof-in-protobuf
2. https://news.ycombinator.com/item?id=18188519

**Comment by AdrianRaFo** [comment]
The right protobuff syntax would be 
```
oneof value {
  A a = 1;
  B B = 2;
}
```
and AFAIK skeuomorph will generate the coproduct without `Option`s. Am I wrong @rafaparadela?

**Comment by rafaparadela** [comment]
I agree that optional values in Coproducts is redundant and doesn't make sense.

We might want to keep this:

```scala
case ProtobufF.TNamedType(name) => TOption(A.algebra(TNamedType(name)))
```

but maybe we should just optimize the printer for Coproducts

**Comment by rafaparadela** [comment]
In the case that @pepegar and @BeniVF approve this approach, this is the PR that closes this issue:
https://github.com/higherkindness/skeuomorph/pull/119
