### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by rafaparadela** [higherkindness/skeuomorph#162]
We would like to have more descriptive documentation for Skeuomorph. The purpose of this issue is to enhance the current documentation, to let newcomers understand what this library does, and how to take advantage of the features.

**Comment by juanpedromoreno** [comment]
👍 We might want to document all the known discrepancies and incompatibilities between the protobuf/avro specs, and proto2/proto3.

**Comment by naree** [comment]
Linking one of the known issues.

https://github.com/higherkindness/skeuomorph/issues/218
