### ISSUE TITLE
make sure tut compiles README

### ISSUE THREAD

**Issue by pepegar** [higherkindness/skeuomorph#22]
In #21 @rlmark noticed that we were not compiling the readme as part of the `tut` task.  We need to fix that.

(as inspiration, we can use [Hammock's build.sbt](https://github.com/pepegar/hammock/blob/master/build.sbt#L223-L234))

**Comment by rlmark** [comment]
Closed by #29. For reference: if you're making changes to the readme code example, you can check if your code compiles by running `sbt readme/tut`.
