### ISSUE TITLE
Unescaped 'type' keyword in package (directory) name

### ISSUE THREAD

**Issue by Dr-Nikson** [higherkindness/skeuomorph#288]
Hello! I tried to generate scala files with latest `mu-scala`and I've faced this error:

```
Failed to parse package name: <input>:1: error: identifier expected but type found
google.logging.type
               ^
```

This error raises when it tries to process  this file - [google/logging/type/http_request.proto](https://github.com/googleapis/api-common-protos/blob/master/google/logging/type/http_request.proto). Package name (directory) contains `type` keyword so we are not able to properly parse it [here](https://github.com/higherkindness/skeuomorph/blob/4be96aa413b68cc469003da3f138647cdc3e4ef5/src/main/scala/higherkindness/skeuomorph/mu/codegen.scala#L49-L53):

```
val packageName = protocol.pkg // "google.logging.type"
      .getOrElse("proto")
      .parse[Term]
      .toEither
      .leftMap(e => s"Failed to parse package name: $e")
      .flatMap(_.as[Term.Ref])
```

As far as these protos comes with kinda "standard" google library (https://github.com/googleapis/api-common-protos) `skeuomorph` have to process it properly

**Comment by Dr-Nikson** [comment]
@juanpedromoreno  Is there anything I could help with?
It seems like `skeuomorph` already has some "escaping" stuff, maybe if you can point me where to start I can fix&PR it by myself

**Comment by juanpedromoreno** [comment]
Hi @Dr-Nikson , thanks for reporting this bug, I triaged it but completely forgot to reply/address the issue.

I've just submitted https://github.com/higherkindness/skeuomorph/pull/305

**Comment by Dr-Nikson** [comment]
@juanpedromoreno so, thank you :) You're doing a really good job with this lib 👍🏼

As I can see [`mu-scala`](https://github.com/higherkindness/mu-scala/releases/tag/v0.22.3) was released today, but https://github.com/higherkindness/sbt-mu-srcgen wasn't. Can I ask you to bump dependencies to ship this release to production? Or I can make a PR by myself if it's make sense somehow

**Comment by juanpedromoreno** [comment]
Yeah, the mu-scala artifacts were just released, and they should go on its way to maven central. As soon as they are ready, @ scala-steward (or any of us) can submit to PR updating the libraries.

**Comment by juanpedromoreno** [comment]
https://github.com/higherkindness/sbt-mu-srcgen/pull/68

**Comment by Dr-Nikson** [comment]
@juanpedromoreno thank you so much for this!)
