### ISSUE TITLE
Parse proto files

### ISSUE THREAD

**Issue by pepegar** [higherkindness/skeuomorph#30]
It would be great to have a way to parse protocol buffers in
Skeuomorph!

This task would involve several smaller tasks to be completed (we can
address each one in a separate PR if we like):

- [ ] compile the proto file into its binary format
- [ ] get a `FileDescriptorProto` out of it
- [ ] convert all message declarations into `ProtobufF` declarations.
- [ ] create a protocol describing a Protobuf file.
- [ ] create transformation between Protobuf's protocol and Mu's
      protocol.

## Compile proto file

To do this we can use [protoc-jar][protoc] as a library.

## Convert proto bytes into a FileDescriptorProto

`FileDescriptorProto` comes from protobuf-java library, the oficial
SDK for protobuf in Java.  The idea would be to use
`FileDescriptorProto.parseFrom` to convert from the bytes generated
with protoc compilation into something with more semantics, like a
`FileDescriptorProto`.

## Convert message declarations to ProtobufF

This is done with a Droste's `Coalgebra`, and the process would be
similar to the one we are doing for avro [here][fromAvro].

## Create a skeuomorph.protobuf.Protocol

This should be similar to [Avro's][AvroProtocol].

## Conversion Protobuf -> Mu

This should be similar to [Mu's fromAvroProtocol][fromAvroProtocol]

[protoc]: https://github.com/os72/protoc-jar#usage---api
[FileDescriptorProto.parseFrom]: https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/DescriptorProtos.FileDescriptorProto#parseFrom-byte:A-
[fromAvro]: https://github.com/higherkindness/skeuomorph/blob/master/src/main/scala/avro/schema.scala#L155
[AvroProtocol]: https://github.com/higherkindness/skeuomorph/blob/master/src/main/scala/avro/Protocol.scala
[fromAvroProtocol]: https://github.com/higherkindness/skeuomorph/blob/master/src/main/scala/mu/protocol.scala#L44

Thanks @AdrianRaFo for https://github.com/AdrianRaFo/proton, from which I pulled the inspiration to create this issue _a la_ skeuomorph

**Comment by AdrianRaFo** [comment]
Proton uses `sbt-protoc` and `scalapb` behind the scenes to read the proto file so it can be helpful to discover how to proceed in some cases

**Comment by juanpedromoreno** [comment]
This has been completed by https://github.com/higherkindness/skeuomorph/pull/66
