### ISSUE TITLE
Invalid enums generated if `package` option is not supplied

### ISSUE THREAD

**Issue by a7emenov** [higherkindness/skeuomorph#337]
After #318 was merged one can successfully generate Scala classes from `.proto` files without having to provide the `package` option. However, this option is still mandatory when generating enum fields in messages as otherwise the resulting field type will be `higherkindness.mu.rpc.protocol.Empty`. 

An example is provided below (note the `enum` field type of the `Example` message):

----
Sample file 1 (invalid generation):
```proto
syntax = "proto3";

message Example {
    ExampleEnum enum = 1;
}

enum ExampleEnum {
    Option1 = 0;
    Option2 = 1;
}
```

Expected result:
```scala
object example {
  final case class Example(@_root_.pbdirect.pbIndex(1) enum: _root_.scala.Option[_root_.example.example.ExampleEnum])
  sealed abstract class ExampleEnum(val value: _root_.scala.Int) extends _root_.enumeratum.values.IntEnumEntry
  object ExampleEnum extends _root_.enumeratum.values.IntEnum[ExampleEnum] {
    case object Option1 extends ExampleEnum(0)
    case object Option2 extends ExampleEnum(1)
    val values = findValues
  }
}
```

Actual result:
```scala
object example {
  final case class Example(@_root_.pbdirect.pbIndex(1) enum: _root_.higherkindness.mu.rpc.protocol.Empty.type)
  sealed abstract class ExampleEnum(val value: _root_.scala.Int) extends _root_.enumeratum.values.IntEnumEntry
  object ExampleEnum extends _root_.enumeratum.values.IntEnum[ExampleEnum] {
    case object Option1 extends ExampleEnum(0)
    case object Option2 extends ExampleEnum(1)
    val values = findValues
  }
}
```

----
Sample file 2 (valid generation):
```proto
syntax = "proto3";

package example;

message Example {
    ExampleEnum enum = 1;
}

enum ExampleEnum {
    Option1 = 0;
    Option2 = 1;
}

```

Result :
```scala
object example {
  final case class Example(@_root_.pbdirect.pbIndex(1) enum: _root_.scala.Option[_root_.example.example.ExampleEnum])
  sealed abstract class ExampleEnum(val value: _root_.scala.Int) extends _root_.enumeratum.values.IntEnumEntry
  object ExampleEnum extends _root_.enumeratum.values.IntEnum[ExampleEnum] {
    case object Option1 extends ExampleEnum(0)
    case object Option2 extends ExampleEnum(1)
    val values = findValues
  }
}
```

**Comment by dmarticus** [comment]
Oh interesting!  Y'know, I don't actually know if we've supported enums in proto source generation before (seems like we _should_), but I'll have to double check with the project specs.  Just to confirm, this change wasn't a regression from #318, right?  I imagine you couldn't generate code with enums ever, correct?

**Comment by dmarticus** [comment]
AH I read this issue more carefully today and I think I know exactly what is going on here; I think I missed a case of checking for packages when parsing more involved data structures.  I'm gonna take a crack at this this weekend!
