### ISSUE TITLE
Improve package and directory structure

### ISSUE THREAD

**Issue by L-Lavigne** [higherkindness/skeuomorph#40]
Our package structure does not match our directory structure, for example in the file `src/main/scala/mu/print.scala`:
```
package skeuomorph
package mu
```

This causes various inconveniences such as ScalaTest/Specs2 integration in IntelliJ IDEA being unable to identify and run tests together from the `src/test` root.

We also use [chained package declarations](https://www.artima.com/scalazine/articles/chained_package_clauses_in_scala.html) which is somewhat non-standard, and it might be worth revisiting that choice.

A re-arrangement of packages would also be a good time to change the package roots once we've agreed internally on a naming convention for `higherkindness`, as part of #18.

Similar suggestion for `mu`: https://github.com/higherkindness/mu/issues/480.

**Comment by JesusMtnez** [comment]
@L-Lavigne if I am understanding this correctly, it means moving things to `src/main/scala/higherkindness/skeumorph/mu` for the example, right?

**Comment by L-Lavigne** [comment]
That's right, assuming we've agreed on the `higherkindness` prefix.

As described I'd also like to change the package declarations to the standard style unless we have a good reason to keep the chained style.

**Comment by JesusMtnez** [comment]
Perfect then. About the package declarations, I agree on using standard style. There is not any special reason,   as far as I know.
