### ISSUE TITLE
No support for M1 Macs

### ISSUE THREAD

**Issue by ThatScalaGuy** [higherkindness/skeuomorph#559]
Hi,

protoc-jar is not actively maintained anymore. The community created a PR to add M1 support. But the maintainer is asking for financial sponsorship instead of merging the PR. 

In my opinion, a quick fix would be to set the protoc version explicitly. Google provides an M1 build starting from version 3.17 (protoc-jar default 3.14). I think, protoc jar will also look up in the Google repository.

**Comment by fedefernandez** [comment]
@ThatScalaGuy thanks for the heads up, I'll take a look

**Comment by ThatScalaGuy** [comment]
@fedefernandez I created a small fix feel free to use it.

 https://github.com/higherkindness/skeuomorph/pull/560

**Comment by fedefernandez** [comment]
Version `0.1.3` is on its way to maven central. @ThatScalaGuy thanks!

**Comment by fedefernandez** [comment]
@ThatScalaGuy just an update. I've released the last piece of the puzzle (`sbt-mu-srcgen`) and everything should be fine soon
