### ISSUE TITLE
openapi Sum type generation is broken for scala 2.13.11

### ISSUE THREAD

**Issue by JLofgren** [higherkindness/skeuomorph#746]
openapi Sum type Encoders print without an explicit type of the json `Aux` instances currently. e.g.

```scala
      type ExampleSum = String :+: Boolean :+: CNil
      object ExampleSum {

        import ...

        implicit val ExampleSumEncoder: Encoder[ExampleSum] = Encoder.instance { x =>
          import shapeless.Poly1
          object json extends Poly1 {

            implicit def string = at[String](x => Encoder[String].apply(x))

            implicit def boolean = at[Boolean](x => Encoder[Boolean].apply(x))
          }
          x.fold(json)
        }
       ...
      }
```

This is resulting in a compiler error starting with scala 2.13.11: `Implicit definition should have explicit type (inferred ....json.Case.Aux[String,io.circe.Json])`

I've opened this PR with a proposed test change to cover the issue: https://github.com/higherkindness/skeuomorph/pull/745

**Comment by dzanot** [comment]
https://github.com/higherkindness/skeuomorph/pull/745 merged
