### ISSUE TITLE
Release v0.2.2

### ISSUE THREAD

**Issue by dzanot** [higherkindness/skeuomorph#758]
We are needing the fix from https://github.com/higherkindness/skeuomorph/issues/746 to upgrade an app's scala version. I can see the draft but I'm not sure how to trigger the release: https://github.com/higherkindness/skeuomorph/releases/tag/untagged-c63df2faf687c89f4678

**Comment by fedefernandez** [comment]
Done!

**Comment by dzanot** [comment]
Thanks!
