### ISSUE TITLE
Decoders for OpenAPI

### ISSUE THREAD

**Issue by fedefernandez** [higherkindness/skeuomorph#79]
There are [encoders](https://github.com/higherkindness/skeuomorph/blob/master/src/main/scala/higherkindness/skeuomorph/openapi/JsonEncoders.scala)

**Comment by BeniVF** [comment]
**Achievements**
- We can encode and decode from the [open api specification 3.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md).
- We can read the specification in a _json_ format
- We can handle parameters, request and response bodies

**To improve**
- Support all the types (e.g. **Licence**, **Contact**, **Example**, **XML Object**) and fields to be able to _decode and re-encode_ back from any open specification 3.0 examples
- Better support for the **Schema Object**
- To be able to read the specification in a _Yaml_ support
- Use the _droste scalacheck_ library to generate fix elements.
