### ISSUE TITLE
The proto and avro printers need to receive a new param for setting the idiomatic gRPC to true

### ISSUE THREAD

**Issue by fedefernandez** [higherkindness/skeuomorph#85]
Relates to https://github.com/higherkindness/mu/issues/599

We need a way for indicating to the printers that the generated `@service` annotation should be populated with the `namespace` and `methodNameStyle` params.

Ideally, it should be a flag called something like `useIdiomaticRPC` that when true it'll put set the `namespace` equal to `Some($package)` and `methodNameStyle` to `Capitalize`. When false, it can omit those params.

After a talk with @juanpedromoreno, we thought the printer could receive some kind of metadata object with this flag and potentially others.

**Comment by pepegar** [comment]
Sounds good to me. Currently printers are in a very raw state, and they’d need this.

**Comment by fedefernandez** [comment]
This was addressed at https://github.com/higherkindness/skeuomorph/pull/101
