### ISSUE TITLE
Improve Option support for Proto2

### ISSUE THREAD

**Issue by TannerYoung** [higherkindness/skeuomorph#89]
Source generated code from Mu creates case classes with member variables of the base type not wrapped in an Option. Scalapb code generation (https://scalapb.github.io/generated-code.html) creates case classes where each proto2 optional field is wrap in an Option, with the default value being None. Additionally the default case class value for each sequence is Nil. 

Doing this makes instantiating case classes a better experience when using proto2, as you don't have to specify each field to be used.

**Comment by juanpedromoreno** [comment]
@noelmarkham Did https://github.com/higherkindness/skeuomorph/pull/92 covered this? Thanks :)

**Comment by noelmarkham** [comment]
Yes, that's right. I'll close this ticket as it's done and released now.

**Comment by noelmarkham** [comment]
@TannerYoung Mu version `0.18.1` should cover this for you, thanks!

**Comment by TannerYoung** [comment]
Apologies for taking two quarters to get back to this, I originally just implemented this myself using generated code from scalapb for the sources and some hacks with the srcgen library. I'm trying to use just mu now, but it doesn't look like the fix actually made the fields options in either proto2 or proto3. I'm using mu 0.19.1:

Proto file:
```
syntax = "proto2";

package src.main.hello;

message SayHelloRequest {
  optional string name = 1;
}
message SayHelloResponse {
  optional string message = 1;
}

service HelloWorldService {
  rpc SayHello (SayHelloRequest) returns (SayHelloResponse) {}
}
```

Generator source:

```
import java.io.File

import higherkindness.mu.rpc.idlgen.Model.UseIdiomaticEndpoints
import higherkindness.mu.rpc.idlgen._
import higherkindness.mu.rpc.idlgen.proto._

object MuSrcGenerator {
  def main(args: Array[String]) {
    val protoFiles: Set[File] = args(1).split(",")
        .map(s => new File(s)).toSet

    println(s"Creating from proto files: $protoFiles")
    println
    val generator = ProtoSrcGenerator.build(Model.NoCompressionGen, UseIdiomaticEndpoints(true), new File(""))
    val result = generator.generateFrom(protoFiles, "")
    result.foreach(println)
    println
    println("Done..")
  }
}
```

Result:

```
Creating from proto files: Set(src/main/hello/hello_world_service.proto)

protoc-jar: protoc version: 3.8.0, detected platform: linux-x86_64 (linux/amd64)
protoc-jar: embedded: bin/3.8.0/protoc-3.8.0-linux-x86_64.exe
protoc-jar: executing: [/tmp/protocjar5745704459137956851/bin/protoc.exe, --proto_path=src/main/hello, --proto_path=/home/tanner/.cache/bazel/_bazel_tanner/1a2508ac388df9662693ef64541f3864/sandbox/linux-sandbox/76/execroot/__main__, --plugin=protoc-gen-proto2_to_proto3, --include_imports, --descriptor_set_out=hello_world_service.proto.desc, hello_world_service.proto]
(src/main/hello/hello_world_service.proto,src/main/hello/hello_world_service.scala,List(package src.main.hello
import higherkindness.mu.rpc.protocol._
import fs2.Stream
import shapeless.{:+:, CNil}



object hello_world_service { 

@message final case class SayHelloRequest(name: String)
@message final case class SayHelloResponse(message: String)
@service(Protobuf, Identity, namespace = Some("src.main.hello"), methodNameStyle = Capitalize) trait HelloWorldService[F[_]] {
  def SayHello(req: SayHelloRequest): F[SayHelloResponse]
}

}))

Done..
```
 

I would have expected `@message final case class SayHelloRequest(name: Option[String])`, is there something I missed reading through the commits and pull requests, some option I should have enabled?

Apologies for commenting on a closed issue.
